{
 "title": "Loan - Traffic",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests (range)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"loan-backend\"} | json | http_status != `` [$__range]))"
    }
   ]
  },
  {
   "title": "Errors 5xx (range)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"loan-backend\"} | json | http_status =~ `5..` [$__range]))"
    }
   ]
  },
  {
   "title": "Request rate by status (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (http_status) (rate({app=\"loan-backend\"} | json | http_status != `` [1m]))",
     "legendFormat": "{{http_status}}"
    }
   ]
  },
  {
   "title": "Latency ms (p50 / p95)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.5, {app=\"loan-backend\"} | json | http_status != `` | unwrap latency_ms [1m])",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile_over_time(0.95, {app=\"loan-backend\"} | json | http_status != `` | unwrap latency_ms [1m])",
     "legendFormat": "p95"
    }
   ]
  }
 ]
}